name: CI

on:
  push:

jobs:
  # Unit test and lints
  unit-testing:
    if: github.event_name == 'push'
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yml
    with:
      job: unit-testing
    secrets: inherit

  lint-code:
    if: github.event_name == 'push'
    name: Lint code
    uses: ./.github/workflows/lint-code.yml
    with:
      job: lint-code
    secrets: inherit
