name: CI

on:
  push:

jobs:
  unit-testing:
    name: Unit Tests
    uses: ./.github/workflows/CI/unit-tests.yml
    with:
      job: unit-testing
    secrets: inherit

  lint-code:
    name: Lint code
    uses: ./.github/workflows/CI/lint-code.yml
    with:
      job: lint-code
    secrets: inherit
