name: Lint code

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  lint-code:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint --exit-zero flaskr/** tests/**

      - name: Lint with black
        run: |
          pip install black
          python -m black --check --experimental-string-processing -l 100 .