name: Slack notification

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["master", "develop", "slack"]
    types:
      - completed

jobs:
  slack-on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ github.event.workflow_run.jobs_url }}\n${{ github.event.workflow_run.html_url || github.event.workflow_run.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ github.event.workflow_run.jobs_url }}\n${{ github.event.workflow_run.html_url || github.event.workflow_run.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  - name: Run echo object
      run: echo ${{ github.event.workflow_run }}

# on:
#   pull_request_review:
#     types: [submitted]

#   jobs:
#   approved:
#     if: github.event.review.state == 'approved'
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "This PR was approved" 
