name: Slack

on:
  push:

jobs:
  slack-on-failure:
    name: Slack notification on CI failure
    uses: ./.github/workflows/slack/CI-on-failure.yml
    with:
      job: slack-on-failure
    secrets: inherit

  pr-review-submited:
    name: Slack notification on Pull Request Review
    uses: ./.github/workflows/slack/PR-review.yml
    with:
      job: pr-review-submited
    secrets: inherit